name: scan_ticket_mobile
description: A mobile app for scanning and managing receipts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_riverpod: ^2.4.9
  # Network
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_cache_manager: ^3.3.1
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.19.0
  logger: ^2.0.2+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
